//! Self-hosting wizard (Feature Y).
//!
//! Generates the files a user needs to host the NyxProxy AI backend on
//! their own infrastructure: a `Dockerfile`, a `docker-compose.yml`, and
//! a `.env.example` with every supported provider key listed.
//!
//! The wizard is **pure** — it does not read or write files itself, so
//! it is trivially testable. The Tauri layer is responsible for writing
//! the rendered strings to disk.

use serde::{Deserialize, Serialize};

/// User-supplied settings for the generated stack.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct SelfHostConfig {
    /// Public port the backend should bind to. Defaults to `8000`.
    pub port: u16,
    /// Whether to include a Caddy reverse-proxy with automatic TLS.
    pub enable_caddy: bool,
    /// Hostname the Caddy proxy should answer for. Ignored when
    /// `enable_caddy` is false. Should be a real DNS-resolvable name
    /// (e.g. `nyx.example.com`).
    pub caddy_host: Option<String>,
    /// Whether to bundle a Cloudflare Tunnel sidecar (`cloudflared`).
    pub enable_cloudflare_tunnel: bool,
    /// Persist `data/` (issue history, scope, etc.) across container
    /// restarts via a named volume.
    pub persistent_data_volume: bool,
}

impl Default for SelfHostConfig {
    fn default() -> Self {
        Self {
            port: 8000,
            enable_caddy: false,
            caddy_host: None,
            enable_cloudflare_tunnel: false,
            persistent_data_volume: true,
        }
    }
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct SelfHostBundle {
    pub dockerfile: String,
    pub compose: String,
    pub env_example: String,
    pub caddyfile: Option<String>,
    pub readme: String,
}

const PROVIDER_KEYS: &[&str] = &[
    "GROQ_API_KEY",
    "OPENROUTER_API_KEY",
    "HF_TOKEN",
    "CLOUDFLARE_API_TOKEN",
    "CLOUDFLARE_ACCOUNT_ID",
    "GITHUB_MODELS_TOKEN",
    "NVIDIA_API_KEY",
    "BYTEZ_API_KEY",
    "GEMINI_API_KEY",
    "OLLAMA_BASE_URL",
    "NYX_BACKEND_TOKEN",
];

pub fn render(cfg: &SelfHostConfig) -> SelfHostBundle {
    SelfHostBundle {
        dockerfile: dockerfile(cfg),
        compose: compose(cfg),
        env_example: env_example(),
        caddyfile: if cfg.enable_caddy {
            Some(caddyfile(cfg))
        } else {
            None
        },
        readme: readme(cfg),
    }
}

fn dockerfile(cfg: &SelfHostConfig) -> String {
    format!(
        r#"# Generated by NyxProxy self-hosting wizard.
# Builds the AI gateway backend (FastAPI + uvicorn).

FROM python:3.12-slim AS base
ENV PYTHONUNBUFFERED=1 \
    PYTHONDONTWRITEBYTECODE=1 \
    PIP_NO_CACHE_DIR=1 \
    PORT={port}

WORKDIR /app
COPY apps/backend/pyproject.toml apps/backend/README.md ./
COPY apps/backend/nyxproxy_backend ./nyxproxy_backend
RUN pip install --upgrade pip && pip install .

EXPOSE {port}
HEALTHCHECK --interval=30s --timeout=5s --retries=3 \
    CMD python -c "import urllib.request; urllib.request.urlopen('http://127.0.0.1:{port}/health').status"

CMD ["uvicorn", "nyxproxy_backend.main:app", "--host", "0.0.0.0", "--port", "{port}"]
"#,
        port = cfg.port,
    )
}

fn compose(cfg: &SelfHostConfig) -> String {
    let mut out = String::new();
    out.push_str("# Generated by NyxProxy self-hosting wizard.\n");
    out.push_str("services:\n");
    out.push_str("  backend:\n");
    out.push_str("    build:\n");
    out.push_str("      context: .\n");
    out.push_str("      dockerfile: Dockerfile\n");
    out.push_str("    restart: unless-stopped\n");
    out.push_str("    env_file:\n");
    out.push_str("      - .env\n");
    if cfg.enable_caddy {
        out.push_str("    expose:\n");
        out.push_str(&format!("      - \"{}\"\n", cfg.port));
    } else {
        out.push_str("    ports:\n");
        out.push_str(&format!("      - \"{port}:{port}\"\n", port = cfg.port));
    }
    if cfg.persistent_data_volume {
        out.push_str("    volumes:\n");
        out.push_str("      - nyxproxy_data:/app/data\n");
    }
    if cfg.enable_caddy {
        out.push_str("\n  caddy:\n");
        out.push_str("    image: caddy:2-alpine\n");
        out.push_str("    restart: unless-stopped\n");
        out.push_str("    ports:\n");
        out.push_str("      - \"80:80\"\n");
        out.push_str("      - \"443:443\"\n");
        out.push_str("    volumes:\n");
        out.push_str("      - ./Caddyfile:/etc/caddy/Caddyfile:ro\n");
        out.push_str("      - caddy_data:/data\n");
        out.push_str("      - caddy_config:/config\n");
        out.push_str("    depends_on:\n");
        out.push_str("      - backend\n");
    }
    if cfg.enable_cloudflare_tunnel {
        out.push_str("\n  cloudflared:\n");
        out.push_str("    image: cloudflare/cloudflared:latest\n");
        out.push_str("    restart: unless-stopped\n");
        out.push_str("    command: tunnel --no-autoupdate run\n");
        out.push_str("    environment:\n");
        out.push_str("      - TUNNEL_TOKEN=${CLOUDFLARE_TUNNEL_TOKEN}\n");
        out.push_str("    depends_on:\n");
        out.push_str("      - backend\n");
    }
    let needs_volumes_block = cfg.persistent_data_volume || cfg.enable_caddy;
    if needs_volumes_block {
        out.push_str("\nvolumes:\n");
        if cfg.persistent_data_volume {
            out.push_str("  nyxproxy_data: {}\n");
        }
        if cfg.enable_caddy {
            out.push_str("  caddy_data: {}\n");
            out.push_str("  caddy_config: {}\n");
        }
    }
    out
}

fn env_example() -> String {
    let mut s = String::from("# NyxProxy backend env file (generated).\n");
    s.push_str("# Fill in only the providers you want available.\n");
    s.push_str("ALLOWED_ORIGINS=*\n\n");
    for key in PROVIDER_KEYS {
        s.push_str(&format!("{key}=\n"));
    }
    s.push_str("\n# Optional: bearer token clients must present.\n");
    s.push_str("# Leave blank to disable auth (not recommended for public deployments).\n");
    s.push_str("NYX_BACKEND_TOKEN=\n");
    s
}

fn caddyfile(cfg: &SelfHostConfig) -> String {
    let host = cfg
        .caddy_host
        .clone()
        .unwrap_or_else(|| "nyx.example.com".to_string());
    format!(
        r#"# Generated by NyxProxy self-hosting wizard.
{host} {{
    encode zstd gzip
    reverse_proxy backend:{port}
    header {{
        Strict-Transport-Security "max-age=63072000"
        X-Content-Type-Options "nosniff"
        Referrer-Policy "no-referrer"
    }}
}}
"#,
        host = host,
        port = cfg.port,
    )
}

fn readme(cfg: &SelfHostConfig) -> String {
    let mut s = String::from("# Self-hosted NyxProxy backend\n\n");
    s.push_str("Generated by the NyxProxy self-hosting wizard. Three files:\n\n");
    s.push_str("- `Dockerfile` — builds the FastAPI gateway\n");
    s.push_str("- `docker-compose.yml` — runs it (");
    if cfg.enable_caddy {
        s.push_str("with Caddy reverse-proxy + automatic TLS");
    } else {
        s.push_str("plain HTTP");
    }
    if cfg.enable_cloudflare_tunnel {
        s.push_str(", plus a Cloudflare Tunnel sidecar");
    }
    s.push_str(")\n");
    s.push_str("- `.env` — fill in your provider keys (copy from `.env.example`)\n");
    if cfg.enable_caddy {
        s.push_str("- `Caddyfile` — Caddy reverse-proxy config\n");
    }
    s.push_str("\n## Boot\n\n```\ncp .env.example .env\n# edit .env\ndocker compose up -d --build\n```\n\n");
    s.push_str(&format!(
        "Backend will be available at `http://YOUR_HOST:{port}/health` once the container is healthy.\n",
        port = cfg.port,
    ));
    if cfg.enable_caddy {
        let host = cfg
            .caddy_host
            .clone()
            .unwrap_or_else(|| "nyx.example.com".to_string());
        s.push_str(&format!(
            "\nWith Caddy enabled, also reachable at `https://{host}/` once DNS points at this host.\n",
            host = host,
        ));
    }
    s.push_str("\nPoint your NyxProxy desktop client at this URL in **User options → Backend URL**.\n");
    s
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn default_bundle_has_expected_files() {
        let b = render(&SelfHostConfig::default());
        assert!(b.dockerfile.contains("python:3.12-slim"));
        assert!(b.dockerfile.contains("uvicorn"));
        assert!(b.compose.contains("services:"));
        assert!(b.compose.contains("backend"));
        assert!(b.compose.contains("8000:8000"));
        assert!(b.env_example.contains("GROQ_API_KEY="));
        assert!(b.env_example.contains("NYX_BACKEND_TOKEN="));
        assert!(b.caddyfile.is_none());
        assert!(b.readme.contains("Self-hosted"));
    }

    #[test]
    fn custom_port_propagates_everywhere() {
        let cfg = SelfHostConfig {
            port: 9000,
            ..SelfHostConfig::default()
        };
        let b = render(&cfg);
        assert!(b.dockerfile.contains("PORT=9000"));
        assert!(b.dockerfile.contains("EXPOSE 9000"));
        assert!(b.compose.contains("9000:9000"));
        assert!(b.readme.contains(":9000"));
    }

    #[test]
    fn caddy_emits_caddyfile_and_https_ports() {
        let cfg = SelfHostConfig {
            enable_caddy: true,
            caddy_host: Some("example.test".to_string()),
            ..SelfHostConfig::default()
        };
        let b = render(&cfg);
        assert!(b.caddyfile.is_some());
        let caddy = b.caddyfile.unwrap();
        assert!(caddy.contains("example.test"));
        assert!(caddy.contains("reverse_proxy backend:8000"));
        assert!(b.compose.contains("caddy:"));
        assert!(b.compose.contains("\"443:443\""));
        // backend should NOT publish its own port when Caddy is in front.
        assert!(!b.compose.contains("8000:8000"));
    }

    #[test]
    fn cloudflare_tunnel_emits_sidecar() {
        let cfg = SelfHostConfig {
            enable_cloudflare_tunnel: true,
            ..SelfHostConfig::default()
        };
        let b = render(&cfg);
        assert!(b.compose.contains("cloudflared:"));
        assert!(b.compose.contains("CLOUDFLARE_TUNNEL_TOKEN"));
    }

    #[test]
    fn no_persistent_volume_drops_volume_block() {
        let cfg = SelfHostConfig {
            persistent_data_volume: false,
            ..SelfHostConfig::default()
        };
        let b = render(&cfg);
        assert!(!b.compose.contains("nyxproxy_data"));
    }
}
